In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,r2_score

In [34]:
df = pd.read_csv("student-mat.csv")
df["sex"] = (df["sex"].str.lower() == "m").astype(int)
df

    school  sex  age address famsize  ... health  absences  G1  G2  G3
0       GP    0   18       U     GT3  ...      3         6   5   6   6
1       GP    0   17       U     GT3  ...      3         4   5   5   6
2       GP    0   15       U     LE3  ...      3        10   7   8  10
3       GP    0   15       U     GT3  ...      5         2  15  14  15
4       GP    0   16       U     GT3  ...      5         4   6  10  10
..     ...  ...  ...     ...     ...  ...    ...       ...  ..  ..  ..
390     MS    1   20       U     LE3  ...      4        11   9   9   9
391     MS    1   17       U     LE3  ...      2         3  14  16  16
392     MS    1   21       R     GT3  ...      3         3  10   8   7
393     MS    1   18       R     LE3  ...      5         0  11  12  10
394     MS    1   19       U     LE3  ...      5         5   8   9   9

[395 rows x 33 columns]

In [49]:
clean_df = df[["studytime","traveltime","failures","absences","health","freetime","goout","G1","G2","G3"]]
clean_df

     studytime  traveltime  failures  absences  ...  goout  G1  G2  G3
0            2           2         0         6  ...      4   5   6   6
1            2           1         0         4  ...      3   5   5   6
2            2           1         3        10  ...      2   7   8  10
3            3           1         0         2  ...      2  15  14  15
4            2           1         0         4  ...      2   6  10  10
..         ...         ...       ...       ...  ...    ...  ..  ..  ..
390          2           1         2        11  ...      4   9   9   9
391          1           2         0         3  ...      5  14  16  16
392          1           1         3         3  ...      3  10   8   7
393          1           3         0         0  ...      1  11  12  10
394          1           1         0         5  ...      3   8   9   9

[395 rows x 10 columns]

In [50]:
x_train,x_test,y_train,y_test = train_test_split(clean_df.drop(["G3"],axis=1),clean_df["G3"],test_size=0.4,random_state=42)

In [51]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled

array([[ 1.10325943, -0.58121007, -0.46112765, ..., -0.15482174,
         0.61493736,  0.59958441],
       [-1.27376316, -0.58121007, -0.46112765, ..., -0.15482174,
        -0.3253217 , -0.20173987],
       [-0.08525187,  0.85365229, -0.46112765, ...,  1.63506859,
        -0.3253217 , -0.73595605],
       ...,
       [-0.08525187, -0.58121007,  2.2710537 , ...,  1.63506859,
        -0.63874138, -0.46884796],
       [ 1.10325943, -0.58121007, -0.46112765, ..., -0.15482174,
         0.61493736,  1.1338006 ],
       [-1.27376316, -0.58121007, -0.46112765, ..., -0.15482174,
        -0.3253217 ,  0.59958441]])

In [52]:
model = LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [53]:
y_train_pred = model.predict(x_train_scaled)

In [54]:
mse = mean_squared_error(y_train,y_train_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_train,y_train_pred)
print(f"mse: {mse},  rmse: {rmse},  r2: {r2}")

mse: 3.2376290049688023,  rmse: 1.7993412697342333,  r2: 0.8400501135673175

In [55]:
y_test_pred = model.predict(scaler.transform(x_test))

In [56]:
mse = mean_squared_error(y_test,y_test_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_test_pred)
print(f"mse: {mse},  rmse: {rmse},  r2: {r2}")

mse: 4.0960989132435115,  rmse: 2.0238821391680673,  r2: 0.813439006631556

In [58]:
import pickle

# Save trained model
with open("model//burnout_model.pkl", "wb") as f:
    pickle.dump(model, f)

# Save fitted scaler
with open("model//scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# Save feature order (very important)
features = ["studytime","traveltime","failures","absences",
            "health","freetime","goout","G1","G2"]

with open("model//features.pkl", "wb") as f:
    pickle.dump(features, f)

print("Model, scaler, and features saved successfully.")

Model, scaler, and features saved successfully.